Vehicle Cooldown
psforever/PSF-LoginServer pull request #771
Opened 2021-04-17 12:45 UTC by Fate-JH

The purchase timer for a vehicle is no longer applied on an unfulfilled vehicle purchase.  It only get set once the player is seated in the vehicle and, if they do not get seated through the prescribed method (vehicle spawn pad protocol), it does not get get applied.

The branch is called `cooldown-reset` because originally the purchase timer was still levied at purchase confirmation but, if the order was cancelled, then the cooldown was cancelled too (reset).  This workflow was reverted as no reason requires setting the timer early.  We could use it for communicating that the purchase went through but that confirmation already is performed visually through the automatic closing the terminal interface.

2021-04-17 23:38 UTC, jgillich requested changes

2021-04-18 02:56 UTC, Fate-JH commented on src/main/scala/net/psforever/actors/session/SessionActor.scala
> +            sendResponse(AvatarVehicleTimerMessage(player.GUID, vehicle.Definition.Name, cooldown.toSeconds, unk1 = true))
I was just moving code from one block to the other.
Looking at that `AvatarActor` code now, do we have to refresh every cooldown each time we update for a specific one?  It feels like that could be better.

2021-04-18 03:06 UTC, jgillich commented on src/main/scala/net/psforever/actors/session/SessionActor.scala
> +            sendResponse(AvatarVehicleTimerMessage(player.GUID, vehicle.Definition.Name, cooldown.toSeconds, unk1 = true))
It's possible I left that in there. And yes, we could definitely update AvatarActor to only send the timer that changed

2021-04-18 13:16 UTC, Fate-JH commented on src/main/scala/net/psforever/actors/session/SessionActor.scala
> +            sendResponse(AvatarVehicleTimerMessage(player.GUID, vehicle.Definition.Name, cooldown.toSeconds, unk1 = true))
Only the message is sent now.

2021-04-19 02:46 UTC, jgillich requested changes

2021-04-19 02:46 UTC, jgillich commented on src/main/scala/net/psforever/actors/session/AvatarActor.scala
> +      avatar.copy(purchaseTimes = avatar.purchaseTimes.removedAll(keysToDrop))
```scala
avatar = avatar.copy(purchaseTimes = avatar.purchaseTimes.removedAll(keysToDrop))
```

2021-04-19 11:39 UTC, merged